spring:
  application:
    name: token-transfer-indexer
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
infura:
  apiKey:
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.demo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/tokenIndexerApp.log